name: LibC

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-libc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      SYSROOT: ${{ github.workspace }}/example/sysroot

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build LibC (Release)
        run: |
          echo "SYSROOT=$SYSROOT"
          mkdir -p $SYSROOT
          
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DLIBC_TARGET=example -DCMAKE_INSTALL_PREFIX=$SYSROOT ..
          
          cmake --build .
          cmake --install .

      - name: Package sysroot
        run: |
          cd "$(dirname "$SYSROOT")"
          zip -r sysroot.zip "$(basename "$SYSROOT")"

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: example-sysroot
          path: ${{ github.workspace }}/example/sysroot.zip

  generate-docs:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Only run this job if the previous job was successful
    needs: build-libc

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install epstopdf
        run: sudo apt-get update && sudo apt-get install -y texlive-font-utils

      - name: Generate Docs
        run: |
          cd toolchain
          ls
          ls ../
          ls ../docs
          ls ../docs/doxy
          ./make_documentation.sh

      - name: Update Progress
        run: |
          cd toolchain
          ./progress.sh --output jsons

      - name: Upload to branch

        # Only upload if this is not a pull request (i.e., it's a push to main)
        if: github.event_name != 'pull_request'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: docs/doxy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"